MWT-24 Fixes
mesosphere/dcos-jenkins-service pull request #320
Opened 2020-04-13 08:39 UTC by kaiwalyajoshi

- Add support for mesos-agent-labels to spawn jenkins tasks on `windows` or `linux` agents with the default being `linux`.
- Update service options to reflect the changes done in version 4.0.0 of dcos-jenkins-service.
- Add group creation support to `sdk_marathon` to allow creation of quota-enforced `jenkins` group.
- Update security settings to use newer `mesos-jenkins` supported version of secrets.

2020-04-14 08:16 UTC, jeschkies commented on conftest.py
> +    parser.addoption(
Is this really required? I don't mind but the service configures two Jenkins agent labels anyways.

2020-04-14 08:40 UTC, jeschkies requested changes
I don't think this addresses the issues of placing the Jenkins master, though. How can I force the master *not* to run on Windows? Please see https://jira.d2iq.com/browse/D2IQ-66928

2020-04-14 16:09 UTC, jeschkies approved these changes

2020-04-15 05:49 UTC, kaiwalyajoshi commented
Everything looks :rocket: for MWT-24, just waiting on the results of the scale test before merging this PR!

2020-04-15 13:28 UTC, jeschkies commented on conf/jenkins/configuration.yaml
> +        agentUser: "${JENKINS_AGENT_USER:-nobody}"
@kaiwalyajoshi, I think the default should be `nobody`.

2020-04-17 04:36 UTC, kaiwalyajoshi commented
Merging this branch into `4.x.y` as we were able to get 500 jenkins master and around 2k executors running.

2020-04-17 04:49 UTC, merged